In [19]:
import scipy
import librosa
import pandas as pd
import os
import numpy as np
from tqdm.notebook import tqdm
import scipy.io.wavfile
import time
import IPython
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torch.utils.data.dataset import Subset
import json
from utils import AudioProcessing, audioPreprocessing, voting
from dataset import audioDataSet
from models import *
from helper import train_audio, evaluate_audio


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)

Using device: cuda

In [20]:
public_test_set = pd.read_csv('/content/public_test_set.csv')

# Task2

In [21]:
model_pth = './weights/task2.pth'

model_pretrained = mbv2_ca(in_c=8, num_classes=4)
model_pretrained.load_state_dict(torch.load(model_pth))
model_pretrained.to(device)
model_pretrained.eval()

voting_dir = './results'
os.makedirs(voting_dir, exist_ok=True)
audio_folder = '/content/drive/MyDrive/COSRMAL_CHALLENGE/test_pub/audio'

tsk2_list = voting(audio_folder, voting_dir, model_pretrained, device, save_size=64)

# Save to pandas
tsk2_np = np.array(tsk2_list)
public_test_set.iloc[:, 4] = (tsk2_np==0).astype(np.int)
public_test_set.iloc[:, 5] = (tsk2_np==1).astype(np.int)
public_test_set.iloc[:, 6] = (tsk2_np==2).astype(np.int)
public_test_set.iloc[:, 7] = (tsk2_np==3).astype(np.int)
public_test_set.iloc[:, 8] = tsk2_np
public_test_set.head()

elapsed_time:266.4312198162079sec

   Configuration ID  Container capacity  ...  Angle difference  Execution time
0                 0                  -1  ...                -1              -1
1                 1                  -1  ...                -1              -1
2                 2                  -1  ...                -1              -1
3                 3                  -1  ...                -1              -1
4                 4                  -1  ...                -1              -1

[5 rows x 20 columns]